Clarify on where the .env file needs to be created.
Made the mistake of creating a `.env` file in the root directory and when I tried to run `npx prisma migrate save --experimental --name "init"` it would result in the following:
```
Error: Get config {"is_panic":false,"message":"error: Environment variable not found: DATABASE_URL.\n  -->  schema.prisma:7\n   | \n 6 |   provider = \"postgresql\"\n 7 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Environment variable not found: DATABASE_URL.\n  -->  schema.prisma:7\n   | \n 6 |   provider = \"postgresql\"\n 7 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
```

Look me awhile to figure out that I needed to add the .env file in the prisma directory.

This is probably a noob mistake but I thought I would bring this up.